export const CREATE_PRODUCER = 'CREATE PRODUCER';
export const UPDATE_PRODUCER = 'UPDATE_PRODUCER';
export const RETRIEVE_PRODUCER = 'RETRIEVE_PRODUCER';
export const DELETE_PRODUCER = 'DELETE_PRODUCER';
